import EthCryptographySpecs.Bls.Pairing
import EthCryptographySpecs.Proofs.Bls.FrZMod
import EthCryptographySpecs.Proofs.Bls.G1Group

/-!
# Sufficiency of the ceremony pairing checks

This file formalizes the algebraic soundness argument behind the
[`kzg-ceremony-specs` sequencer pairing checks](https://github.com/ethereum/kzg-ceremony-specs/blob/master/docs/sequencer/sequencer.md#pairing-checks).

Unlike an exponent-only model, the statement below is phrased over this repository's
actual `Bls.Fr`, `Bls.G1`, `Bls.G2`, `Bls.G1.mul`, `Bls.G2.mul`, and
`Bls.pairingCheck` definitions.

The repository does not yet prove bilinearity, non-degeneracy, or scalar-multiplication
faithfulness for its executable BLS12-381 implementation. Those concrete implementation
properties are therefore collected in `ConcreteBlsLaws`. The main theorem proves that,
once those exact missing laws are supplied, the three concrete pairing checks force every
submitted point to be the expected power of the updated trapdoor.

The theorem concerns the exact, unbatched checks. Soundness of random-linear-combination
batching is a separate probabilistic statement.
-/

namespace EthCryptographySpecs.Kzg.CeremonyChecks

open EthCryptographySpecs.Bls (Fr G1 G2)
open scoped EthCryptographySpecs.Bls.Fr

/-- Equality of two pairings, expressed using the repository's product-pairing checker.

`pairingEq p₁ q₁ p₂ q₂` represents `e(p₁, q₁) = e(p₂, q₂)` as
`e(p₁, q₁) * e(-p₂, q₂) = 1`. -/
def pairingEq (p₁ : G1) (q₁ : G2) (p₂ : G1) (q₂ : G2) : Prop :=
  EthCryptographySpecs.Bls.pairingCheck #[(p₁, q₁), (G1.neg p₂, q₂)] = true

/-- A single submitted ceremony contribution, using the repository's concrete point
representations. -/
structure Contribution where
  g1Powers : Array G1
  g2Powers : Array G2
  potPubkey : G2

/-- The part of the previous transcript used by the tau-update check. -/
structure Transcript where
  previousTau : G1

/-- The three sequencer pairing checks over concrete G1/G2 points.

The size hypotheses make every checked index explicit and avoid the silent-truncation
behavior of pseudocode `zip`. -/
structure Checks (contribution : Contribution) (transcript : Transcript) : Prop where
  one_lt_g1 : 1 < contribution.g1Powers.size
  one_lt_g2 : 1 < contribution.g2Powers.size
  g2_le_g1 : contribution.g2Powers.size ≤ contribution.g1Powers.size

  /-- Tau update:
  `e(previousTau, potPubkey) = e(g1Powers[1], G2.generator)`. -/
  tauUpdate :
    pairingEq transcript.previousTau contribution.potPubkey
      (contribution.g1Powers[1]'one_lt_g1) G2.generator

  /-- G1 recurrence:
  `e(g1Powers[i+1], G2.generator) = e(g1Powers[i], g2Powers[1])`. -/
  g1Powers : ∀ i (hi : i + 1 < contribution.g1Powers.size),
    pairingEq
      (contribution.g1Powers[i + 1]'hi) G2.generator
      (contribution.g1Powers[i]'(Nat.lt_trans (Nat.lt_succ_self i) hi))
      (contribution.g2Powers[1]'one_lt_g2)

  /-- G1/G2 consistency:
  `e(G1.generator, g2Powers[i]) = e(g1Powers[i], G2.generator)`. -/
  g2Powers : ∀ i (hi : i < contribution.g2Powers.size),
    pairingEq G1.generator
      (contribution.g2Powers[i]'hi)
      (contribution.g1Powers[i]'(Nat.lt_of_lt_of_le hi g2_le_g1))
      G2.generator

/-- Scalar exponents witnessing that the checked points belong to the prime-order cyclic
subgroups generated by `G1.generator` and `G2.generator`.

This uses the repository's actual scalar field `Bls.Fr`; it does not introduce a second
scalar model. A future formal subgroup-membership development can construct this witness
from the concrete subgroup checks. -/
structure SubgroupExponents
    (contribution : Contribution) (transcript : Transcript) where
  s : Fr
  x : Fr
  a : Nat → Fr
  b : Nat → Fr
  previousTau_eq : transcript.previousTau = G1.mul G1.generator s
  potPubkey_eq : contribution.potPubkey = G2.mul G2.generator x
  g1_eq : ∀ i (hi : i < contribution.g1Powers.size),
    contribution.g1Powers[i]'hi = G1.mul G1.generator (a i)
  g2_eq : ∀ i (hi : i < contribution.g2Powers.size),
    contribution.g2Powers[i]'hi = G2.mul G2.generator (b i)

/-- Scalar multiplication by one gives the concrete G1 generator.

This follows from the existing `G1.mulNat_def` unfolding theorem rather than
being assumed by `ConcreteBlsLaws`. -/
private theorem g1Mul_one : G1.mul G1.generator (1 : Fr) = G1.generator := by
  change G1.mulNat G1.generator 1 = G1.generator
  rw [G1.mulNat_def]
  norm_num
  rw [G1.mulNat_def]
  norm_num
  rfl

/-- Unfolding equation for the executable G2 double-and-add multiplication. -/
private theorem g2MulNat_def (p : G2) (k : Nat) :
    G2.mulNat p k = if k = 0 then G2.zero
      else if k % 2 = 1 then G2.add p (G2.mulNat (G2.double p) (k / 2))
      else G2.mulNat (G2.double p) (k / 2) := by
  rw [G2.mulNat]

/-- Scalar multiplication by one gives the concrete G2 generator. -/
private theorem g2Mul_one : G2.mul G2.generator (1 : Fr) = G2.generator := by
  change G2.mulNat G2.generator 1 = G2.generator
  rw [g2MulNat_def]
  norm_num
  rw [g2MulNat_def]
  norm_num
  rfl

/-- The concrete BLS implementation laws required by the proof.

Every field refers directly to this repository's `G1.mul`, `G2.mul`, `isInfinity`, and
`pairingCheck` (through `pairingEq`). Proving this structure for the executable pairing
implementation is the remaining cryptographic verification obligation; it is no longer
hidden behind an unrelated abstract pairing type. -/
structure ConcreteBlsLaws : Prop where
  /-- A generator multiple is non-infinity exactly when its scalar is nonzero. -/
  g1Mul_nonzero_iff : ∀ s : Fr,
    G1.isInfinity (G1.mul G1.generator s) = false ↔ s ≠ 0

  /-- A generator multiple is non-infinity exactly when its scalar is nonzero. -/
  g2Mul_nonzero_iff : ∀ x : Fr,
    G2.isInfinity (G2.mul G2.generator x) = false ↔ x ≠ 0

  /-- The single bilinearity/non-degeneracy bridge used for all three checks.

  This states the semantics of the repository's concrete `pairingCheck` when all
  inputs are prime-subgroup generator multiples. -/
  pairingEq_mul_iff : ∀ a b c d : Fr,
    pairingEq
      (G1.mul G1.generator a) (G2.mul G2.generator b)
      (G1.mul G1.generator c) (G2.mul G2.generator d) ↔
      a * b = c * d

/-- **Scalar consequence of all three concrete pairing checks.**

This is the algebraic core of `checksSufficient`, but its hypotheses are already phrased
in terms of the repository's concrete points and `Bls.pairingCheck`. -/
theorem exponentChecksSufficient
    (laws : ConcreteBlsLaws)
    (contribution : Contribution) (transcript : Transcript)
    (checks : Checks contribution transcript)
    (exponents : SubgroupExponents contribution transcript)
    (previousTauNonzero : G1.isInfinity transcript.previousTau = false)
    (pubkeyNonzero : G2.isInfinity contribution.potPubkey = false) :
    (∀ i, i < contribution.g1Powers.size →
      exponents.a i = Fr.powNat (exponents.s * exponents.x) i) ∧
    (∀ i, i < contribution.g2Powers.size →
      exponents.b i = Fr.powNat (exponents.s * exponents.x) i) := by
  have s_ne_zero : exponents.s ≠ 0 := by
    apply (laws.g1Mul_nonzero_iff exponents.s).mp
    rw [← exponents.previousTau_eq]
    exact previousTauNonzero

  have x_ne_zero : exponents.x ≠ 0 := by
    apply (laws.g2Mul_nonzero_iff exponents.x).mp
    rw [← exponents.potPubkey_eq]
    exact pubkeyNonzero

  have updateScalar : exponents.s * exponents.x = exponents.a 1 := by
    have h := checks.tauUpdate
    rw [exponents.previousTau_eq, exponents.potPubkey_eq,
      exponents.g1_eq 1 checks.one_lt_g1] at h
    have h' : pairingEq
        (G1.mul G1.generator exponents.s)
        (G2.mul G2.generator exponents.x)
        (G1.mul G1.generator (exponents.a 1))
        (G2.mul G2.generator 1) := by
      simpa only [g2Mul_one] using h
    have hmul :=
      (laws.pairingEq_mul_iff exponents.s exponents.x (exponents.a 1) 1).mp h'
    exact hmul.trans (Fin.mul_one (exponents.a 1))

  have g1Recurrence : ∀ i (hi : i + 1 < contribution.g1Powers.size),
      exponents.a (i + 1) = exponents.a i * exponents.b 1 := by
    intro i hi
    have h := checks.g1Powers i hi
    rw [exponents.g1_eq (i + 1) hi,
      exponents.g1_eq i (Nat.lt_trans (Nat.lt_succ_self i) hi),
      exponents.g2_eq 1 checks.one_lt_g2] at h
    have h' : pairingEq
        (G1.mul G1.generator (exponents.a (i + 1)))
        (G2.mul G2.generator 1)
        (G1.mul G1.generator (exponents.a i))
        (G2.mul G2.generator (exponents.b 1)) := by
      simpa only [g2Mul_one] using h
    have hmul :=
      (laws.pairingEq_mul_iff
        (exponents.a (i + 1)) 1 (exponents.a i) (exponents.b 1)).mp h'
    exact
      calc
        exponents.a (i + 1) = exponents.a (i + 1) * (1 : Fr) :=
          (Fin.mul_one (exponents.a (i + 1))).symm
        _ = exponents.a i * exponents.b 1 := hmul

  have crossGroup : ∀ i (hi : i < contribution.g2Powers.size),
      exponents.b i = exponents.a i := by
    intro i hi
    have h := checks.g2Powers i hi
    rw [exponents.g2_eq i hi,
      exponents.g1_eq i (Nat.lt_of_lt_of_le hi checks.g2_le_g1)] at h
    have h' : pairingEq
        (G1.mul G1.generator 1)
        (G2.mul G2.generator (exponents.b i))
        (G1.mul G1.generator (exponents.a i))
        (G2.mul G2.generator 1) := by
      simpa only [g1Mul_one, g2Mul_one] using h
    have hmul :=
      (laws.pairingEq_mul_iff 1 (exponents.b i) (exponents.a i) 1).mp h'
    exact
      calc
        exponents.b i = (1 : Fr) * exponents.b i :=
          (Fin.one_mul (exponents.b i)).symm
        _ = exponents.a i * (1 : Fr) := hmul
        _ = exponents.a i := Fin.mul_one (exponents.a i)

  let tau : Fr := exponents.s * exponents.x

  have a_one : exponents.a 1 = tau := updateScalar.symm

  have tau_ne_zero : tau ≠ 0 := by
    dsimp [tau]
    intro hzero
    have hmulInv := congrArg (fun z : Fr => z * exponents.x⁻¹) hzero
    have hxInv : exponents.x * exponents.x⁻¹ = 1 :=
      mul_inv_cancel₀ x_ne_zero
    apply s_ne_zero
    calc
      exponents.s = exponents.s * 1 := (Fin.mul_one exponents.s).symm
      _ = exponents.s * (exponents.x * exponents.x⁻¹) :=
        congrArg (fun z : Fr => exponents.s * z) hxInv.symm
      _ = (exponents.s * exponents.x) * exponents.x⁻¹ :=
        (mul_assoc _ _ _).symm
      _ = 0 * exponents.x⁻¹ := hmulInv
      _ = 0 := zero_mul _

  have b_one : exponents.b 1 = exponents.a 1 :=
    crossGroup 1 checks.one_lt_g2

  have a_one_ne_zero : exponents.a 1 ≠ 0 := by
    rw [a_one]
    exact tau_ne_zero

  have a_zero : exponents.a 0 = 1 := by
    have recurrence_zero : exponents.a 1 = exponents.a 0 * exponents.b 1 :=
      g1Recurrence 0 checks.one_lt_g1
    have hcancel : (1 : Fr) * exponents.a 1 =
        exponents.a 0 * exponents.a 1 := by
      calc
        (1 : Fr) * exponents.a 1 = exponents.a 1 := one_mul _
        _ = exponents.a 0 * exponents.b 1 := recurrence_zero
        _ = exponents.a 0 * exponents.a 1 := by rw [b_one]
    have hcancelInv :=
      congrArg (fun z : Fr => z * (exponents.a 1)⁻¹) hcancel
    have haInv : exponents.a 1 * (exponents.a 1)⁻¹ = 1 :=
      mul_inv_cancel₀ a_one_ne_zero
    have one_eq_a_zero : (1 : Fr) = exponents.a 0 := by
      calc
        (1 : Fr) = exponents.a 1 * (exponents.a 1)⁻¹ := haInv.symm
        _ = ((1 : Fr) * exponents.a 1) * (exponents.a 1)⁻¹ := by
          rw [Fin.one_mul]
        _ = (exponents.a 0 * exponents.a 1) * (exponents.a 1)⁻¹ := hcancelInv
        _ = exponents.a 0 * (exponents.a 1 * (exponents.a 1)⁻¹) :=
          mul_assoc _ _ _
        _ = exponents.a 0 * 1 :=
          congrArg (fun z : Fr => exponents.a 0 * z) haInv
        _ = exponents.a 0 := Fin.mul_one _
    exact one_eq_a_zero.symm

  have g1_is_powers : ∀ i, i < contribution.g1Powers.size →
      exponents.a i = Fr.powNat tau i := by
    intro i
    induction i with
    | zero =>
        intro _
        calc
          exponents.a 0 = 1 := a_zero
          _ = Fr.powNat tau 0 := (Fr.powNat_zero tau).symm
    | succ i ih =>
        intro i_succ_lt
        have i_lt : i < contribution.g1Powers.size :=
          Nat.lt_trans (Nat.lt_succ_self i) i_succ_lt
        calc
          exponents.a (i + 1) = exponents.a i * exponents.b 1 :=
            g1Recurrence i i_succ_lt
          _ = exponents.a i * exponents.a 1 := by rw [b_one]
          _ = Fr.powNat tau i * tau := by rw [ih i_lt, a_one]
          _ = tau * Fr.powNat tau i := EthCryptographySpecs.Bls.Fr.mul_comm _ _
          _ = Fr.powNat tau (i + 1) := (Fr.powNat_succ tau i).symm

  have g2_is_powers : ∀ i, i < contribution.g2Powers.size →
      exponents.b i = Fr.powNat tau i := by
    intro i hi
    calc
      exponents.b i = exponents.a i := crossGroup i hi
      _ = Fr.powNat tau i :=
        g1_is_powers i (Nat.lt_of_lt_of_le hi checks.g2_le_g1)

  constructor
  · intro i hi
    simpa [tau] using g1_is_powers i hi
  · intro i hi
    simpa [tau] using g2_is_powers i hi

/-- **Sufficiency of all three concrete pairing checks.**

Assume the previous transcript point and participant public key are non-infinity. If the
three pairing checks hold, then each submitted concrete G1/G2 point is scalar multiplication
of the repository's generator by `(s * x)^i`.

The non-infinity assumptions correspond to validity of the previous transcript and the
sequencer's explicit nonzero-public-key check. -/
theorem checksSufficient
    (laws : ConcreteBlsLaws)
    (contribution : Contribution) (transcript : Transcript)
    (checks : Checks contribution transcript)
    (exponents : SubgroupExponents contribution transcript)
    (previousTauNonzero : G1.isInfinity transcript.previousTau = false)
    (pubkeyNonzero : G2.isInfinity contribution.potPubkey = false) :
    (∀ i (hi : i < contribution.g1Powers.size),
      contribution.g1Powers[i]'hi =
        G1.mul G1.generator (Fr.powNat (exponents.s * exponents.x) i)) ∧
    (∀ i (hi : i < contribution.g2Powers.size),
      contribution.g2Powers[i]'hi =
        G2.mul G2.generator (Fr.powNat (exponents.s * exponents.x) i)) := by
  have scalarPowers := exponentChecksSufficient laws contribution transcript checks
    exponents previousTauNonzero pubkeyNonzero
  constructor
  · intro i hi
    calc
      contribution.g1Powers[i]'hi =
          G1.mul G1.generator (exponents.a i) := exponents.g1_eq i hi
      _ = G1.mul G1.generator
          (Fr.powNat (exponents.s * exponents.x) i) := by
        rw [scalarPowers.1 i hi]
  · intro i hi
    calc
      contribution.g2Powers[i]'hi =
          G2.mul G2.generator (exponents.b i) := exponents.g2_eq i hi
      _ = G2.mul G2.generator
          (Fr.powNat (exponents.s * exponents.x) i) := by
        rw [scalarPowers.2 i hi]

/-- The recurrence and cross-group checks force the zeroth submitted G1 exponent to be
one. -/
theorem g1ZeroExponentEqOne
    (laws : ConcreteBlsLaws)
    (contribution : Contribution) (transcript : Transcript)
    (checks : Checks contribution transcript)
    (exponents : SubgroupExponents contribution transcript)
    (previousTauNonzero : G1.isInfinity transcript.previousTau = false)
    (pubkeyNonzero : G2.isInfinity contribution.potPubkey = false) :
    exponents.a 0 = 1 := by
  have zero_lt_g1 : 0 < contribution.g1Powers.size :=
    Nat.lt_trans (Nat.zero_lt_succ 0) checks.one_lt_g1
  have h := (exponentChecksSufficient laws contribution transcript checks exponents
    previousTauNonzero pubkeyNonzero).1 0 zero_lt_g1
  simpa [Fr.powNat_zero] using h

/-- The zeroth concrete G1 point is scalar multiplication of the generator by one. -/
theorem g1ZeroPointEqGeneratorMulOne
    (laws : ConcreteBlsLaws)
    (contribution : Contribution) (transcript : Transcript)
    (checks : Checks contribution transcript)
    (exponents : SubgroupExponents contribution transcript)
    (previousTauNonzero : G1.isInfinity transcript.previousTau = false)
    (pubkeyNonzero : G2.isInfinity contribution.potPubkey = false) :
    contribution.g1Powers[0]'(Nat.lt_trans (Nat.zero_lt_succ 0) checks.one_lt_g1) =
      G1.mul G1.generator (1 : Fr) := by
  have h := (checksSufficient laws contribution transcript checks exponents
    previousTauNonzero pubkeyNonzero).1 0
      (Nat.lt_trans (Nat.zero_lt_succ 0) checks.one_lt_g1)
  simpa [Fr.powNat_zero] using h

/-- No separate G2 recurrence is needed: the concrete cross-group check transfers the
already-established G1 powers to every supplied G2 point. -/
theorem g2PowersFollowFromCrossGroup
    (laws : ConcreteBlsLaws)
    (contribution : Contribution) (transcript : Transcript)
    (checks : Checks contribution transcript)
    (exponents : SubgroupExponents contribution transcript)
    (previousTauNonzero : G1.isInfinity transcript.previousTau = false)
    (pubkeyNonzero : G2.isInfinity contribution.potPubkey = false) :
    ∀ i (hi : i < contribution.g2Powers.size),
      contribution.g2Powers[i]'hi =
        G2.mul G2.generator (Fr.powNat (exponents.s * exponents.x) i) :=
  (checksSufficient laws contribution transcript checks exponents
    previousTauNonzero pubkeyNonzero).2

end EthCryptographySpecs.Kzg.CeremonyChecks
