import EthCryptographySpecs.Proofs.Bls.G1Group
import EthCryptographySpecs.Proofs.Bls.FrZMod

/-!
# Proofs: the order of the `G1` generator and the `Fr` action

The three facts that make `⟨g₁⟩` an "`Fr`-vector space" in the minimal
form the trusted-setup proofs need:

* `valid_generator`: the spec's generator is a nonsingular curve point
  (kernel-checked arithmetic on the 381-bit coordinates).
* `modulus_smul_generator`: `[r]g₁ = 0` — kernel-checked by running
  the double-and-add ladder through a fuel-based structural model
  (`mulNatAux`), since well-founded recursion does not reduce in the
  kernel. With `r` prime and `g₁ ≠ 0` this pins
  `addOrderOf (toPoint generator) = r` exactly.
* `ofFr`, the map `s ↦ [s.val]g₁`, with `Fr`-linearity laws: scalar
  arithmetic mod `r` acts correctly on the subgroup generated by `g₁`.
-/

namespace EthCryptographySpecs.Bls.G1

open WeierstrassCurve.Jacobian

set_option maxRecDepth 8000

/-! ## Generator validity -/

/-- The spec's generator is a nonsingular point of the curve. -/
theorem valid_generator : Valid generator := by
  show curve.Nonsingular (rep generator)
  rw [nonsingular_iff, equation_iff]
  exact ⟨by decide, Or.inr (Or.inl (by decide))⟩

/-! ## `[r]g₁ = 0` -/

/-- Fuel-based double-and-add, structurally recursive so the kernel
can evaluate it (the spec's `mulNat` is well-founded recursion, which
does not reduce definitionally). Correctness: `mulNatAux_eq`. -/
private def mulNatAux : Nat → G1 → Nat → G1
  | 0, _, _ => zero
  | fuel + 1, p, k =>
    if k = 0 then zero
    else
      let half := mulNatAux fuel (double p) (k / 2)
      if k % 2 = 1 then add p half else half

private theorem mulNatAux_eq (fuel : Nat) (p : G1) (k : Nat)
    (hk : k < 2 ^ fuel) : mulNatAux fuel p k = mulNat p k := by
  induction fuel generalizing p k with
  | zero =>
    have : k = 0 := by simpa using hk
    subst this
    rw [mulNatAux, mulNat_def]
    simp
  | succ fuel ih =>
    rw [mulNatAux, mulNat_def]
    by_cases h0 : k = 0
    · simp [h0]
    · have h2 : k / 2 < 2 ^ fuel := by
        rw [Nat.pow_succ] at hk
        omega
      rw [if_neg h0, if_neg h0, ih (double p) (k / 2) h2]

/-- `[r]g₁` is the point at infinity, checked by the kernel through
the fuel-based ladder: 255 doublings/additions of 381-bit arithmetic. -/
theorem modulus_smul_generator :
    Fr.modulus • toPoint generator = 0 := by
  rw [← toPoint_mulNat valid_generator]
  refine Point.toAffine_of_Z_eq_zero (isZero_iff.mp ?_)
  rw [← mulNatAux_eq 256 generator Fr.modulus (by decide)]
  decide

/-- The generator is not the identity (its representative has
`z = 1 ≠ 0`, so it maps to an affine point). -/
theorem toPoint_generator_ne_zero : toPoint generator ≠ 0 := by
  rw [toPoint, Point.toAffine_of_Z_ne_zero valid_generator
    (by exact fun h => absurd (isZero_iff.mpr h) (by decide))]
  exact fun h => by cases h

/-- The generator has additive order exactly `r`. -/
theorem addOrderOf_toPoint_generator :
    addOrderOf (toPoint generator) = Fr.modulus :=
  addOrderOf_eq_prime modulus_smul_generator toPoint_generator_ne_zero

/-! ## The `Fr` action on `⟨g₁⟩` -/

/-- Scalar multiples of `g₁` only depend on the scalar mod `r`. -/
theorem nsmul_generator_mod (k : Nat) :
    k • toPoint generator = (k % Fr.modulus) • toPoint generator := by
  conv_lhs => rw [← Nat.div_add_mod k Fr.modulus]
  rw [add_nsmul, Nat.mul_comm Fr.modulus (k / Fr.modulus), mul_nsmul',
      modulus_smul_generator, nsmul_zero, zero_add]

/-- The image of a scalar in the curve group: `ofFr s = [s]g₁`.
`WellFormed` trusted-setup statements are phrased with this map. -/
noncomputable def ofFr (s : Fr) : curve.toAffine.Point :=
  s.val • toPoint generator

theorem ofFr_zero : ofFr 0 = 0 := zero_nsmul _

theorem ofFr_one : ofFr 1 = toPoint generator := one_nsmul _

/-- `ofFr` is additive: `Fr` addition (mod `r`) matches group
addition. -/
theorem ofFr_add (s t : Fr) : ofFr (s + t) = ofFr s + ofFr t := by
  rw [ofFr, ofFr, ofFr, show (s + t).val = (s.val + t.val) % Fr.modulus from rfl,
      ← nsmul_generator_mod, add_nsmul]

/-- `ofFr` intertwines `Fr` multiplication with the scalar action. -/
theorem ofFr_mul (s t : Fr) : ofFr (s * t) = s.val • ofFr t := by
  rw [ofFr, ofFr, show (s * t).val = s.val * t.val % Fr.modulus from rfl,
      ← nsmul_generator_mod, mul_nsmul']

/-- The spec's scalar multiplication of the generator is `ofFr`. -/
theorem toPoint_mul_generator (s : Fr) :
    toPoint (mul generator s) = ofFr s :=
  toPoint_mulNat valid_generator s.val

/-! ## Reference multi-scalar multiplication

`msmRef` is the naive fold `Σ_i [sᵢ]Pᵢ`; `toPoint_msmRef` maps it to a
`Finset.sum` in the curve group. The spec's windowed-Pippenger `msm`
will be proved equal to `msmRef` separately (that proof is about the
bucketing algorithm, not about the group). -/

/-- Naive multi-scalar multiplication: `Σ_i [scalars i] (points i)`
over the first `n` indices. -/
def msmRef (points : Nat → G1) (scalars : Nat → Fr) : Nat → G1
  | 0 => zero
  | n + 1 => add (msmRef points scalars n) (mul (points n) (scalars n))

theorem valid_msmRef {points : Nat → G1} (scalars : Nat → Fr)
    (hp : ∀ i, Valid (points i)) (n : Nat) :
    Valid (msmRef points scalars n) := by
  induction n with
  | zero => exact valid_zero
  | succ n ih => exact valid_add ih (valid_mul (hp n) _)

/-- The reference MSM computes the sum of the scalar multiples in the
curve group. -/
theorem toPoint_msmRef {points : Nat → G1} (scalars : Nat → Fr)
    (hp : ∀ i, Valid (points i)) (n : Nat) :
    toPoint (msmRef points scalars n)
      = ∑ i ∈ Finset.range n, (scalars i).val • toPoint (points i) := by
  induction n with
  | zero =>
    rw [Finset.range_zero, Finset.sum_empty]
    exact toPoint_zero
  | succ n ih =>
    rw [msmRef, toPoint_add (valid_msmRef scalars hp n) (valid_mul (hp n) _),
        ih, toPoint_mul (hp n), Finset.sum_range_succ]

end EthCryptographySpecs.Bls.G1
